name: actions test1

on: [push]

jobs:
  run-github-actions1:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action 1
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: michael
      - name: log output time
        run: echo "${{steps.greet.outputs.time}}"
      - name: show envs
        run: |
          echo $GITHUB_SHA  
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          git clone git@github:$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA
          ls -a
